const express = require('express');
const router = express.Router();
const multer = require('multer');
const axios = require('axios');
const FormData = require('form-data');
const { verifyAdmin } = require('../middleware/verifyAdmin');

// Use memory storage so files are temporarily held in RAM to be sent to cPanel
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 } // 10MB limit per file
});

const uploadFields = upload.fields([
  { name: 'deliveryNote', maxCount: 1 },
  { name: 'deliveryPicture', maxCount: 1 }
]);

const db = require('../db'); 

// Helper function to push files to your cPanel PHP receiver
async function sendFilesToCPandel(files) {
  const formData = new FormData();

  if (files['deliveryNote']) {
    const note = files['deliveryNote'][0];
    formData.append('deliveryNote', note.buffer, {
      filename: note.originalname,
      contentType: note.mimetype,
    });
  }

  if (files['deliveryPicture']) {
    const pic = files['deliveryPicture'][0];
    // Note: PHP script looks for 'deliveryPhotos[]' or single file depending on your setup. 
    // Here we map deliveryPicture to deliveryPhotos[] to match your PHP script.
    formData.append('deliveryPhotos[]', pic.buffer, {
      filename: pic.originalname,
      contentType: pic.mimetype,
    });
  }

  // Send to your live cPanel PHP receiver endpoint with secret token auth
  const response = await axios.post('https://mxk.dpn.mybluehost.me/api/upload_receiver.php', formData, {
    headers: {
      ...formData.getHeaders(),
      'Authorization': 'Bearer GSE-DATABASE-2021'
    }
  });

  if (response.data && response.data.success) {
    return response.data.files; // Returns URLs generated by cPanel
  }
  throw new Error('Failed to upload files to cPanel receiver');
}

// 1. GET ALL DELIVERIES
router.get('/deliveries', async (req, res) => {
  try {
    const [rows] = await db.query('SELECT * FROM deliveries ORDER BY delivery_date DESC');
    res.json({ success: true, data: rows });
  } catch (error) {
    console.error('Error fetching deliveries:', error);
    res.status(500).json({ success: false, message: 'Server error fetching deliveries' });
  }
});

// 2. CREATE DELIVERY
router.post('/deliveries', uploadFields, async (req, res) => {
  try {
    let { deliveryDate, quotationNumber, companyName, status } = req.body;
    
    if (deliveryDate) {
      deliveryDate = deliveryDate.split('T')[0];
    }
    
    let deliveryNoteUrl = null;
    let deliveryPictureUrl = null;

    // If files were uploaded, stream them to cPanel first
    if (req.files && (req.files['deliveryNote'] || req.files['deliveryPicture'])) {
      const cPanelFiles = await sendFilesToCPandel(req.files);
      deliveryNoteUrl = cPanelFiles.deliveryNote || null;
      if (cPanelFiles.deliveryPhotos && cPanelFiles.deliveryPhotos.length > 0) {
        deliveryPictureUrl = cPanelFiles.deliveryPhotos[0];
      }
    }

    const query = `
      INSERT INTO deliveries (delivery_date, quotation_number, company_name, status, delivery_note, delivery_picture)
      VALUES (?, ?, ?, ?, ?, ?)
    `;

    const [result] = await db.query(query, [
      deliveryDate, 
      quotationNumber, 
      companyName, 
      status || 'Pending', 
      deliveryNoteUrl, 
      deliveryPictureUrl
    ]);

    res.status(201).json({ 
      success: true, 
      message: 'Delivery created and files uploaded to cPanel successfully', 
      deliveryId: result.insertId 
    });
  } catch (error) {
    console.error('Error creating delivery:', error);
    res.status(500).json({ success: false, message: 'Server error creating delivery' });
  }
});

// 3. UPDATE DELIVERY
router.put('/deliveries/:id', uploadFields, async (req, res) => {
  try {
    const { id } = req.params;
    let { deliveryDate, quotationNumber, companyName, status } = req.body;

    if (deliveryDate) {
      deliveryDate = deliveryDate.split('T')[0];
    }

    const [existing] = await db.query('SELECT * FROM deliveries WHERE id = ?', [id]);
    if (existing.length === 0) {
      return res.status(404).json({ success: false, message: 'Delivery record not found' });
    }

    let deliveryNoteUrl = existing[0].delivery_note;
    let deliveryPictureUrl = existing[0].delivery_picture;

    // If new files are uploaded, send them to cPanel
    if (req.files && (req.files['deliveryNote'] || req.files['deliveryPicture'])) {
      const cPanelFiles = await sendFilesToCPandel(req.files);
      if (cPanelFiles.deliveryNote) {
        deliveryNoteUrl = cPanelFiles.deliveryNote;
      }
      if (cPanelFiles.deliveryPhotos && cPanelFiles.deliveryPhotos.length > 0) {
        deliveryPictureUrl = cPanelFiles.deliveryPhotos[0];
      }
    }

    const query = `
      UPDATE deliveries 
      SET delivery_date = ?, quotation_number = ?, company_name = ?, status = ?, delivery_note = ?, delivery_picture = ?
      WHERE id = ?
    `;

    await db.query(query, [
      deliveryDate, 
      quotationNumber, 
      companyName, 
      status, 
      deliveryNoteUrl, 
      deliveryPictureUrl, 
      id
    ]);

    res.json({ success: true, message: 'Delivery updated successfully' });
  } catch (error) {
    console.error('Error updating delivery:', error);
    res.status(500).json({ success: false, message: 'Server error updating delivery' });
  }
});

// 4. DELETE DELIVERY
router.delete('/deliveries/:id', verifyAdmin, async (req, res) => {
  try {
    const { id } = req.params;
    await db.query('DELETE FROM deliveries WHERE id = ?', [id]);
    res.json({ success: true, message: 'Delivery deleted successfully' });
  } catch (error) {
    console.error('Error deleting delivery:', error);
    res.status(500).json({ success: false, message: 'Server error deleting delivery' });
  }
});

module.exports = router;